<form action="<?= $block->getFormAction() ?>" method="post">
    <input type="text" name="first_name" placeholder="First Name" required maxlength="30" />
    <input type="text" name="last_name" placeholder="Last Name" required maxlength="30" />
    <input type="email" name="email_id" placeholder="Email" required />
    <textarea name="address" placeholder="Address" required minlength="30"></textarea>
    <input type="text" name="phone_number" placeholder="Phone Number" required pattern="\d{10}" />
    <button type="submit">Save</button>
</form>